"""Initial migration.

Revision ID: 1b38639d752c
Revises: 
Create Date: 2024-01-25 01:38:11.175942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b38639d752c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_model', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
